### ISSUE TITLE
Bugs found in twitter_api.js wrapper

### ISSUE THREAD

**Issue by bsavas** [mogya/tm_twitter_api#1]
1. Change "http://api.twitter.com/version/account/verify_credentials.json" to "http://api.twitter.com/1/account/verify_credentials.json"
2. Change "http://api.twitter.com/version/favorites.json" to "http://api.twitter.com/1/favorites.json" 
3. Change "http://api.twitter.com/version/friendships/create.json" to "http://api.twitter.com/1/friendships/create.json"

**Comment by mogya** [comment]
Thanks. also, this.blocks_blocking should be this.blocks_blocking_ids
I'll release tomorow for these bugs.

**Comment by bsavas** [comment]
Okay, thanks!

**Comment by mogya** [comment]
Here it is.
https://github.com/mogya/tm_twitter_api/commit/e0b25cb20dbdfee6fff837542c9613240fcaa996
